# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:13.3.0-browsers

    working_directory: ~/JISSAY_REP

    steps:
      - checkout:
          path: ~/JISSAY_REP/

      # Perform build
      - run: npm install
      - run: node_modules/@angular/cli/bin/ng build
      # Save build and node modules to cache
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  test:
      docker:
        - image: circleci/node:13.3.0-browsers

      steps:
        - checkout
        - attach_workspace:
            at: .

        # run tests!
        - run: npm install
        - run: node_modules/@angular/cli/bin/ng test

        - store_test_results:
            path: test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build